# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# @help: https://docs.docker.com/compose/compose-file

name: my_music_tool

services:
  cpp:
    build:
      additional_contexts:
        rs: "../../rs/"
      context: ../
      dockerfile: ./docker/Dockerfile
      # platforms:
      #   - "linux/amd64"
      #   - "linux/arm64"
      target: deps
    image: ghcr.io/fruzitent/my_music_tool-cpp:latest
    pull_policy: if_not_present
    restart: always
    volumes:
      - type: volume
        source: cpp_data
        target: /workspaces/
        volume:
          nocopy: true
      - type: bind
        source: ../../rs/
        target: /workspaces/rs/
        read_only: true

volumes:
  cpp_data:
