set(CPACK_PROPERTIES_FILE "${CMAKE_BINARY_DIR}/CPackProperties.local.cmake")

include(InstallRequiredSystemLibraries)
include(CPack)

file(
    WRITE
    "${CPACK_PROPERTIES_FILE}"
    "\
include(${GIT_WATCHER_OUTPUT_PATH})

set(CPACK_PACKAGE_FILE_NAME \"\")

list(APPEND CPACK_PACKAGE_FILE_NAME \"${CMAKE_PROJECT_NAME}\")
list(APPEND CPACK_PACKAGE_FILE_NAME \"${CMAKE_PROJECT_VERSION}\")

list(APPEND CPACK_PACKAGE_FILE_NAME \"\$\{GIT_DESCRIBE\}\")
if(GIT_IS_DIRTY STREQUAL \"true\")
    list(APPEND CPACK_PACKAGE_FILE_NAME \"dirty\")
endif()

list(APPEND CPACK_PACKAGE_FILE_NAME \"${CMAKE_SYSTEM_PROCESSOR}\")
list(APPEND CPACK_PACKAGE_FILE_NAME \"${CMAKE_SYSTEM_NAME}\")
list(APPEND CPACK_PACKAGE_FILE_NAME \"${CMAKE_CXX_COMPILER_ID}\")
list(APPEND CPACK_PACKAGE_FILE_NAME \"${CMAKE_CXX_COMPILER_VERSION}\")
list(APPEND CPACK_PACKAGE_FILE_NAME \"${CMAKE_BUILD_TYPE}\")

string(REPLACE \";\" \"-\" CPACK_PACKAGE_FILE_NAME \"\$\{CPACK_PACKAGE_FILE_NAME\}\")
"
)
